workflows:
  android-debug:
    name: "Duda — Debug APK"
    max_build_duration: 60
    instance_type: linux_x2

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true

    environment:
      java: 17
      vars:
        GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.caching=true"

    scripts:
      - name: "Verificar Java"
        script: java -version

      - name: "Permissão gradlew"
        script: chmod +x ./gradlew

      - name: "Verificar Gradle Wrapper"
        script: |
          if [ ! -f "./gradle/wrapper/gradle-wrapper.jar" ]; then
            echo "ERRO: gradle-wrapper.jar não encontrado!"
            exit 1
          fi

      - name: "Build Debug APK"
        script: |
          ./gradlew clean :app:assembleDebug \
            --stacktrace \
            --no-daemon \
            -Dorg.gradle.jvmargs="-Xmx4g -XX:+UseParallelGC"

      - name: "Verificar APK gerado"
        script: |
          APK_PATH="app/build/outputs/apk/debug/app-debug.apk"
          if [ -f "$APK_PATH" ]; then
            echo "✅ APK gerado: $APK_PATH"
            ls -lh "$APK_PATH"
          else
            echo "❌ APK NÃO encontrado!"
            find app/build -name "*.apk" 2>/dev/null || true
            exit 1
          fi

    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
      - app/build/reports/**/*
